name: Benchmarks

inputs:
  cpu-label:
    description: "Runner's CPU label"
    required: true
  mem-label:
    description: "Amount of RAM the runner has"
    required: true
  compute-type:
    description: "Type of compute used by the runner (CUDA/Metal/None)"
    default: "None"
    required: false
  token:
    description: "GitHub runner token"
    required: true

runs:
  using: composite
  steps:
    - run: echo "Running on ${{ inputs.cpu-label }} - ${{ inputs.mem-label }} - ${{ inputs.compute-type }}"
      shell: bash
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install Dependencies
      shell: bash
      run: |
        if [ "${{ inputs.cpu-label }}" == "M1" ]; then
          mkdir homebrew && curl -L https://github.com/Homebrew/brew/tarball/master | tar xz --strip 1 -C homebrew
          eval "$(homebrew/bin/brew shellenv)"
          brew install openssl jq gnu-time
          echo "PATH=\"homebrew/bin:$PATH\"" >> $GITHUB_ENV
        else
          sudo apt-get update && sudo apt-get install -y openssl libssl-dev jq time
        fi
    - name: Setup Environment
      shell: bash
      run: |
        python -m venv .env
        source .env/bin/activate
        echo "ENABLE_ICICLE_GPU=${{ inputs.compute-type == 'CUDA' }}" >> $GITHUB_ENV
    - name: Run Benchmarks
      shell: bash
      run: |
        source .env/bin/activate
        case "${{ inputs.compute-type }}" in
          CUDA)
            feature="cuda"
            ;;
          Metal)
            feature="metal"
            ;;
          *)
            feature=""
            ;;
        esac
        if [ -n "$feature" ]; then
          cargo nextest run --features $feature benchmarking_tests::tests --test-threads 1
        else
          cargo nextest run benchmarking_tests::tests --test-threads 1
        fi
    - name: Process Results
      shell: bash
      run: |
        jq '.' benchmarks.json > "benches/${{ inputs.cpu-label }}-${{ inputs.mem-label }}-${{ inputs.compute-type }}.json"
        git config --global user.email "actions@inferencelabs.com"
        git config --global user.name "GitHub Actions"
        git pull
        git add "benches/${{ inputs.cpu-label }}-${{ inputs.mem-label }}-${{ inputs.compute-type }}.json"
        if git diff --staged --quiet; then
          echo "No changes to commit."
        else
          git commit -m "Update benchmarks for ${{ inputs.cpu-label }}-${{ inputs.mem-label }}-${{ inputs.compute-type }}"
          git push
        fi
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
