name: Benchmarks

inputs:
  cpu-label:
    description: "Runner's CPU label"
    required: true
  mem-label:
    description: "Amount of RAM the runner has"
    required: true
  compute-type:
    description: "Type of compute used by the runner (CUDA/Metal/None)"
    default: "None"
    required: false
  token:
    description: "GitHub runner token"
    required: true

runs:
  using: composite
  steps:
    - run: echo "Running on ${{ inputs.cpu-label }} - ${{ inputs.mem-label }} - ${{ inputs.compute-type }}"
      shell: bash
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install Dependencies
      shell: bash
      run: |
        if [ "${{ inputs.cpu-label }}" == "M1" ]; then
          mkdir homebrew && curl -L https://github.com/Homebrew/brew/tarball/master | tar xz --strip 1 -C homebrew
          eval "$(homebrew/bin/brew shellenv)"
          brew install openssl jq gnu-time
          echo "PATH=\"homebrew/bin:$PATH\"" >> $GITHUB_ENV
        else
          sudo apt-get update && sudo apt-get install -y openssl libssl-dev jq time
        fi
    - uses: software-mansion/setup-scarb@v1
      with:
        scarb-version: "2.4.2"
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly-2024-01-16
        override: true
        components: rustfmt, clippy
    - uses: baptiste0928/cargo-install@v1
      with:
        crate: cargo-nextest
        locked: true
    - name: Cargo clean
      shell: bash
      run: cargo clean
    - name: Delete Cargo.lock
      shell: bash
      run: rm -f Cargo.lock
    - name: Install Risc0 toolchain
      shell: bash
      run: |
        cargo install cargo-binstall
        cargo binstall cargo-risczero --no-confirm
        cargo risczero install
    - name: Install Rust jupyter kernel
      shell: bash
      run: |
        cargo install evcxr_jupyter
        evcxr_jupyter --install
    - name: Build ZKML
      shell: bash
      run: cargo build --release
      working-directory: ./src/zkml
    - name: Download and Install EZKL Binary
      shell: bash
      run: |
        curl https://raw.githubusercontent.com/zkonduit/ezkl/main/install_ezkl_cli.sh | bash || true
        sudo mv ${XDG_CONFIG_HOME:-$HOME}/.ezkl/ezkl /usr/local/bin/ || true
        ezkl --version
    - name: Setup Environment
      shell: bash
      run: |
        python -m venv .env
        source .env/bin/activate
        echo "ENABLE_ICICLE_GPU=${{ inputs.compute-type == 'CUDA' }}" >> $GITHUB_ENV
    - name: Run Benchmarks
      shell: bash
      run: |
        source .env/bin/activate
        case "${{ inputs.compute-type }}" in
          CUDA)
            feature="cuda"
            ;;
          Metal)
            feature="metal"
            ;;
          *)
            feature=""
            ;;
        esac
        if [ -n "$feature" ]; then
          cargo nextest run --features $feature benchmarking_tests::tests --test-threads 1
        else
          cargo nextest run benchmarking_tests::tests --test-threads 1
        fi
    - name: Process Results
      shell: bash
      run: |
        jq '.' benchmarks.json > "benches/${{ inputs.cpu-label }}-${{ inputs.mem-label }}-${{ inputs.compute-type }}.json"
        git config --global user.email "actions@inferencelabs.com"
        git config --global user.name "GitHub Actions"
        git pull
        git add "benches/${{ inputs.cpu-label }}-${{ inputs.mem-label }}-${{ inputs.compute-type }}.json"
        if git diff --staged --quiet; then
          echo "No changes to commit."
        else
          git commit -m "Update benchmarks for ${{ inputs.cpu-label }}-${{ inputs.mem-label }}-${{ inputs.compute-type }}"
          git push
        fi
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
