name: Benchmarks
on:
  push:
    branches: ["main"]
    paths-ignore:
      - "README.md"
  pull_request:
    branches: ["main"]
    paths-ignore:
      - "README.md"

env:
  CARGO_TERM_COLOR: always

jobs:
  benchmark-tests:
    runs-on:
      ubuntu-latest-32-cores
      # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        env:
          POSTGRES_USER: ubuntu
          POSTGRES_HOST_AUTH_METHOD: trust
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432
    # needs: [build,  library-tests, docs]
    steps:
      - uses: actions/checkout@v4
      - uses: software-mansion/setup-scarb@v1
        with:
          scarb-version: "2.4.0"
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: rustfmt, clippy
      - uses: baptiste0928/cargo-install@v1
        with:
          crate: cargo-nextest
          locked: true
      - name: Install Risc0 toolchain
        run: |
          cargo install cargo-binstall
          yes | cargo binstall cargo-risczero
          cargo risczero install
      - name: Install Rust jupyter kernel
        run: |
          cargo install evcxr_jupyter
          evcxr_jupyter --install
      - name: Setup Virtual Env
        run: python -m venv .env; source .env/bin/activate;
      # - name: authenticate-kaggle-cli
      #   shell: bash
      #   env:
      #     KAGGLE_API_KEY: ${{ secrets.KAGGLE_API_KEY }}
      #   run: |
      #     mkdir /home/ubuntu/.kaggle
      #     # now dump the contents of the file into a file called kaggle.json
      #     echo $KAGGLE_API_KEY > /home/ubuntu/.kaggle/kaggle.json
      #     chmod 600 /home/ubuntu/.kaggle/kaggle.json
      - name: Run all benchmarks across all models
        run: source .env/bin/activate; cargo nextest run benchmarking_tests::tests::run_benchmarks_ --no-capture