name: Benchmarks
on:
  push:
    branches: ["main"]
    paths-ignore:
      - "README.md"
  pull_request:
    branches: ["main"]
    paths-ignore:
      - "README.md"

env:
  CARGO_TERM_COLOR: always

jobs:
  benchmark-tests:
    runs-on:
      large-self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Remove Existing pyenv Installation
        run: rm -rf /home/ubuntu/.pyenv
      - name: Install dependencies
        run: bash install_dep_run.sh
      - name: Run all benchmarks across all models
        run: source .env/bin/activate; cargo nextest run benchmarking_tests::tests::run_benchmarks_ --no-capture