name: Benchmarks
on:
  push:
    branches: ["main"]
    paths-ignore:
      - "README.md"
  pull_request:
    branches: ["main"]
    paths-ignore:
      - "README.md"

jobs:
  benchmark-16CPU-32GB:
    runs-on: [self-hosted, 16CPU, 32GB]
    steps:
      - uses: actions/checkout@v2
      - name: Run Benchmarks on 16CPU-32GB
        uses: ./.github/actions/bench
        with:
          cpu-label: "16CPU"
          memory-label: "32GB"
  benchmark-cuda:
    runs-on: [self-hosted, CUDA]
    steps:
      - uses: actions/checkout@v2
      - name: Run CUDA Benchmarks
        uses: ./.github/actions/bench
        with:
          cpu-label: "16CPU"
          memory-label: "32GB"
          cuda: "true"
  # benchmark-32CPU-64GB:
  #   runs-on: [self-hosted, 32CPU, 64GB]
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Run Benchmarks on 32CPU-64GB
  #       uses: ./.github/actions/bench
  #       with:
  #         cpu-label: "32CPU"
  #         memory-label: "64GB"
  # benchmark-64CPU-128GB:
  #   runs-on: [self-hosted, 64CPU, 128GB]
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Run Benchmarks on 64CPU-128GB
  #       uses: ./.github/actions/bench
  #       with:
  #         cpu-label: "64CPU"
  #         memory-label: "128GB"
